# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - uses: actions/checkout@v2
      - name: Running tests
        run: |
          echo Starting the tests:
          mkdir bin
          mkdir lib
          curl https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.5.2/junit-platform-console-standalone-1.5.2.jar -o lib/junit-platform-console-standalone-1.5.2.jar
          javac -d bin/ src/Calculator.java
          javac -d bin -cp bin:lib/junit-platform-console-standalone-1.5.2.jar test/*
          java -jar lib/junit-platform-console-standalone-1.5.2.jar --class-path bin --scan-class-path
      
